### ISSUE TITLE
QRS complex peak 

### ISSUE THREAD

**Issue by renatosc** [andr81/qrs_detector#2]
Why is the QRS peak being marked in the plot as the S peak instead of the R peak? (when show_rs_points=False)

**Comment by andr81** [comment]
Hi! This is an implementation from the source repository. The derivative value at peak S is higher than R. But you can use r_point_indices to plot these points.

**Comment by renatosc** [comment]
Yes, I saw your r_point_indices and it works fine. Thanks for it.
